services:
  frontend-dev:
    image: frontend-dev
    build:
      context: ./frontend/
      dockerfile: ./dev.Dockerfile
    volumes:
      - ./frontend/:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
    container_name: frontend-dev
  backend-dev:
    image: backend-dev
    build:
      context: ./backend/
      dockerfile: ./dev.Dockerfile
    volumes:
      - ./backend/:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 4000:4000
    environment:
      - PORT=4000
    container_name: backend-dev
  nginx:  
    image: nginx:1.20.1
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    container_name: reverse-proxy
    