services:
  app:
    image: frontend
    build:
      context: ./frontend/
      dockerfile: ./dev.Dockerfile
    volumes:
      - ./frontend/:/usr/src/app
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
    container_name: frontend
  backend:
    image: backend
    build:
      context: ./backend/
      dockerfile: ./dev.Dockerfile
    volumes:
      - ./backend/:/usr/src/app
    ports:
      - 4000:4000
    container_name: backend
  nginx:  
    image: nginx:1.20.1
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    container_name: reverse-proxy